"""Configuration and filesystem paths.

Everything is overridable via environment variables so tests can point the
tool at a throwaway socket/state directory without touching the real one.
"""

from __future__ import annotations

import os
import shutil
from dataclasses import dataclass, field
from pathlib import Path

ENV_PREFIX = "MULTI_CLAUDE_"


def _env(name: str, default: str) -> str:
    return os.environ.get(ENV_PREFIX + name, default)


@dataclass
class Config:
    # tmux socket name: isolates our server from the user's tmux entirely.
    socket_name: str = field(default_factory=lambda: _env("SOCKET", "multi-claude"))
    # Where instance metadata + generated tmux.conf live.
    data_dir: Path = field(
        default_factory=lambda: Path(
            _env(
                "DATA_DIR",
                os.path.join(
                    os.environ.get("XDG_DATA_HOME", os.path.expanduser("~/.local/share")),
                    "multi-claude",
                ),
            )
        )
    )
    # Command used to launch an instance. Resolved to an absolute path at
    # spawn time because tmux's default shell may not share our PATH (nvm).
    claude_cmd: str = field(default_factory=lambda: _env("CLAUDE_CMD", "claude"))
    # Dashboard poll interval (seconds) for status/preview refresh.
    poll_interval: float = field(
        default_factory=lambda: float(_env("POLL_INTERVAL", "1.0"))
    )
    # Lines of scrollback captured for the preview pane.
    preview_lines: int = 200
    # Ring a bell / notify-send when an instance starts waiting on you.
    notify: bool = field(default_factory=lambda: _env("NOTIFY", "1") != "0")

    @property
    def registry_path(self) -> Path:
        return self.data_dir / "instances.json"

    @property
    def tmux_conf_path(self) -> Path:
        return self.data_dir / "tmux.conf"

    def resolve_claude_cmd(self) -> str | None:
        """Absolute path to the claude binary, or None if not found."""
        return shutil.which(os.path.expanduser(self.claude_cmd))

    def ensure_dirs(self) -> None:
        self.data_dir.mkdir(parents=True, exist_ok=True)


# Contents of the tmux.conf used for OUR server only. Never touches the
# user's tmux configuration.
TMUX_CONF = """\
# Generated by multi-claude; edits are overwritten at dashboard startup.

# Keep panes around when claude exits so we can show EXITED + last output
# and offer a restart (respawn-pane).
set -g remain-on-exit on

# One-keystroke detach back to the dashboard, no prefix needed. Chosen to be
# unlikely to collide: C-q is XON/XOFF flow control, which almost nothing in
# a Claude session uses.
bind-key -n C-q detach-client

set -g mouse on
set -g history-limit 50000
set -g default-terminal "tmux-256color"
set -g escape-time 10

# Minimal inner status line so an attached user knows where they are and how
# to get back.
set -g status on
set -g status-style "bg=colour236,fg=colour250"
set -g status-left "#[bold] multi-claude "
set -g status-left-length 20
set -g status-right " #S  |  C-q: back to dashboard "
set -g status-right-length 60
"""
