"""Configuration and filesystem paths.

Everything is overridable via environment variables so tests can point the
tool at a throwaway socket/state directory without touching the real one.
"""

from __future__ import annotations

import os
import shlex
import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path

ENV_PREFIX = "MULTI_CLAUDE_"

# tmux session layout on our dedicated server:
DASH_SESSION = "mc-dash"     # the dashboard: sidebar pane + viewer pane
DASH_WINDOW = "dash"
WORK_SESSION = "mc-work"     # parking lot: one window per undisplayed instance
SIDEBAR_WIDTH = 34


def _env(name: str, default: str) -> str:
    # An empty value (e.g. an unset shell variable interpolated into env)
    # falls back to the default rather than producing broken settings.
    return os.environ.get(ENV_PREFIX + name) or default


@dataclass
class Config:
    # tmux socket name: isolates our server from the user's tmux entirely.
    socket_name: str = field(default_factory=lambda: _env("SOCKET", "multi-claude"))
    # Where instance metadata + generated tmux.conf live.
    data_dir: Path = field(
        default_factory=lambda: Path(
            _env(
                "DATA_DIR",
                os.path.join(
                    os.environ.get("XDG_DATA_HOME", os.path.expanduser("~/.local/share")),
                    "multi-claude",
                ),
            )
        )
    )
    # Command used to launch an instance. Resolved to an absolute path at
    # spawn time because tmux's default shell may not share our PATH (nvm).
    claude_cmd: str = field(default_factory=lambda: _env("CLAUDE_CMD", "claude"))
    # Dashboard poll interval (seconds) for status refresh.
    poll_interval: float = field(
        default_factory=lambda: float(_env("POLL_INTERVAL", "1.0"))
    )
    # Ring a bell / notify-send when an instance starts waiting on you.
    notify: bool = field(default_factory=lambda: _env("NOTIFY", "1") != "0")

    @property
    def registry_path(self) -> Path:
        return self.data_dir / "instances.json"

    @property
    def tmux_conf_path(self) -> Path:
        return self.data_dir / "tmux.conf"

    def resolve_claude_cmd(self) -> str | None:
        """Absolute path to the claude binary, or None if not found."""
        return shutil.which(os.path.expanduser(self.claude_cmd))

    def ensure_dirs(self) -> None:
        self.data_dir.mkdir(parents=True, exist_ok=True)

    def mc_command(self) -> str:
        """Shell command that re-enters this CLI from tmux run-shell bindings.

        Must work from the tmux server's environment (which has neither our
        PYTHONPATH nor necessarily our PATH), so pin the interpreter, the
        package location, and the env vars that select socket/data dir.
        """
        repo = Path(__file__).resolve().parent.parent
        pinned = {
            f"{ENV_PREFIX}SOCKET": self.socket_name,
            f"{ENV_PREFIX}DATA_DIR": str(self.data_dir),
            f"{ENV_PREFIX}CLAUDE_CMD": self.claude_cmd,
            f"{ENV_PREFIX}POLL_INTERVAL": str(self.poll_interval),
            f"{ENV_PREFIX}NOTIFY": "1" if self.notify else "0",
        }
        parts = (
            ["env", f"PYTHONPATH={shlex.quote(str(repo))}"]
            + [f"{k}={shlex.quote(v)}" for k, v in pinned.items()]
            + [shlex.quote(sys.executable), "-m", "multi_claude"]
        )
        return " ".join(parts)

    def render_tmux_conf(self) -> str:
        mc = self.mc_command()
        select_binds = "\n".join(
            f'bind-key -n M-{n} run-shell "{mc} select {n}"' for n in range(1, 10)
        )
        return TMUX_CONF_TEMPLATE.format(mc=mc, select_binds=select_binds)


# Config for OUR tmux server only; never touches the user's tmux setup.
# All bindings are prefix-less so they work when nested inside the user's
# own tmux session (Alt keys pass straight through an outer tmux).
TMUX_CONF_TEMPLATE = """\
# Generated by multi-claude; edits are overwritten at dashboard startup.

# Keep panes around when claude exits so we can show EXITED + last output
# and offer a restart (respawn-pane).
set -g remain-on-exit on

set -g mouse on
set -g history-limit 50000
set -g default-terminal "tmux-256color"
set -g escape-time 10

# -- dashboard keys (no prefix needed) --------------------------------------
# C-q: detach the dashboard client (everything keeps running).
bind-key -n C-q detach-client
# Alt-h / Alt-l: move focus between the sidebar and the Claude pane.
bind-key -n M-h select-pane -L
bind-key -n M-l select-pane -R
# Alt-z: zoom the focused pane to full screen (again to restore).
bind-key -n M-z resize-pane -Z
# Alt-1..9: display instance N; Alt-o: cycle to the next instance.
{select_binds}
bind-key -n M-o run-shell "{mc} select next"

set -g status on
set -g status-style "bg=colour236,fg=colour250"
set -g status-left "#[bold] multi-claude "
set -g status-left-length 20
set -g status-right " M-h/M-l panes · M-1..9/M-o switch · M-z zoom · C-q detach "
set -g status-right-length 70
"""
